// Code generated by github.com/jmattheis/goverter, DO NOT EDIT.
//go:build !goverter

package main

import api "github.com/sublee/convgen/cmd/vs-goverter/api"

func init() {
	GoverterVersion = func(source User) (api.User, error) {
		var apiUser api.User
		apiUser.Id = uniqueToString(source.ID)
		xstring, err := firstname(source.Name)
		if err != nil {
			return apiUser, err
		}
		apiUser.Firstname = xstring
		xstring2, err := lastname(source.Name)
		if err != nil {
			return apiUser, err
		}
		apiUser.Lastname = xstring2
		if source.URLs != nil {
			apiUser.Urls = make([]string, len(source.URLs))
			for i := 0; i < len(source.URLs); i++ {
				apiUser.Urls[i] = source.URLs[i]
			}
		}
		apiUser.Role = GoverterVersionUserRole(source.Role)
		apiUser.CreatedAt = timeToUnix(source.CreateTime)
		return apiUser, nil
	}
	GoverterVersionUserRole = func(source UserRole) api.UserRole {
		var apiUserRole api.UserRole
		switch source {
		case UserRoleAdmin:
			apiUserRole = api.Admin
		case UserRoleGuest:
			apiUserRole = api.Guest
		case UserRoleMember:
			apiUserRole = api.Member
		case UserRoleUnknown:
			apiUserRole = api.UserRoleUnspecified
		default:
			apiUserRole = api.UserRoleUnspecified
		}
		return apiUserRole
	}
}
