// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0
// source: job.sql

package db

import (
	"context"
)

const getJob = `-- name: GetJob :one
SELECT id, status FROM "job" WHERE "id" = $1
`

func (q *Queries) GetJob(ctx context.Context, id int64) (Job, error) {
	row := q.db.QueryRowContext(ctx, getJob, id)
	var i Job
	err := row.Scan(&i.ID, &i.Status)
	return i, err
}
