name: CI

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.25'

      - name: Lint
        uses: golangci/golangci-lint-action@v8
        with:
          version: v2.4

      - name: Download dependencies
        run: go mod download

      - name: Test
        run: go test ./...
